AWSTemplateFormatversion: '2010-09-09'
Description: Static Website Hosting using s3

Resources:

  MyWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
     BucketName: muni-demo-bucket
     WebsiteConfiguration:
     IndexDocument: index.html
     ErrorDocument: error.html

     BucketPolicy:
     Type: AWS::BucketPolicy
     Properties:
     Bucket: !Ref MyWebsiteBucket
     PolicyDocument:
      Statement:
         "Sid": "PublicRead"
            "Effect": "Allow"
            "Principal": "*"
            "Action": "s3:GetObject"
            "Resource": "arn:aws:s3:::muni-demo-bucket/*"
            -''
             --'arn:aws:s3:::'
             -!Ref MyWebsiteBucket
             -'/*'
             Value:! GetAtt MyWebsiteBucket.WebsiteURL
             Description: URL of the static website             

     
